rag:
  transformer:
    chunk_size: 500
    overlap: 50
    min_chunk_length: 100

  retriever:
    top_k: 5

# gemini global config
gemini:
  apikey: "${GOOGLE_KEY}"
  model: "gemini-2.0-pro"
  embedder: "gemini-embedding-001"

milvus:
  host: "localhost"
  port: 19530
  collection: "rag_docs"


