# RAG system compentent config
rag:
  transformer:
    chunk_size: 500
    overlap: 50
    min_chunk_length: 100

  retriever:
    topk: 5

# gemini global config
gemini:
  apikey: "${GOOGLE_KEY}"
  model: "gemini-2.0-pro"
  embedder: "gemini-embedding-001"
  dim: 3072

# milvus global config
milvus:
  addr: "localhost:19530"
  username: "minioadmin"
  password: "minioadmin"
  collection: "rag_docs"


