# RAG system compentent config
rag:
  transformer:
    chunk_size: 500
    overlap: 50
    min_chunk_length: 100

  retriever:
    topk: 5

  indexer:
    metricType: "COSINE"

# gemini global config
gemini:
  apikey: "${GOOGLE_KEY}"
  model: "gemini-2.0-Flash"
  # embedder: "gemini-embedding-001"
  embedder: "text-embedding-004"
  dim: 1536 

# milvus global config
milvus:
  addr: "localhost:19530"
  username: "minioadmin"
  password: "minioadmin"
  # collection: "rag_docs"
  collection: "test_rag_docs"


